<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>

</body>

</html>
<script>
  function run(gen) {
    let args = [].slice.call(arguments, 1),
      it
    console.log('args: ', args);
    it = gen.apply(this, args)
    console.log('it: ', it);
    return Promise.resolve().then(handleNext = (value) => {
      var next = it.next(value)
      console.log('next: ', next);
      return (handleResult = (next) => {
        if (next.done) {
          return next.value
        } else {
          return Promise.resolve(next.value) // 对值进行包装，确保是一个promise
            .then(handleNext, handleErr = (err) => { //只是在链上把异常捕获并传递下，程序继续正常执行
              return Promise.resolve(
                it.throw(err)
              ).then(handleResult)
            })
        }
      })(next)
    })
  }

  function* f() {
    let a = yield new Promise(function (reolve, reject) {
      setTimeout(() => {
        reolve(3)
      }, 1000)
    })
    // throw new Error('tt')
    let b = a * 3
    console.log(a, 33)
    return b
    // console.log(b, 'b')
  }
  run(f).then(function fulfilled(res) {
    console.log(res, 55)
  }, function reject(reason) {
    console.log(reason)
  })
</script>
